---
# setup compose dir structure
- name: setup compose dir structure
  file:
    # ToDo: replace compose-wordpress path with a variable
    path: compose-wordpress/{{ item }}
    state: directory
    owner: ubuntu
    group: ubuntu
    recurse: yes
    mode: 0755
  with_items:
  - wordpress
  - db-data
  - nginx
  - logs/nginx
  tags:
    - dir_ops

- name: create docker-compose.yml file
  file:
    path: compose-wordpress/docker-compose.yml
    owner: ubuntu
    group: ubuntu
    state: touch
  tags:
    - file_ops

- name: deploy WordPress virtual host
  copy:
    # ToDo: pick up foolcontrol from a variable
    src: files/wordpress.conf
    dest: compose-wordpress/nginx/wordpress.conf
    owner: ubuntu
    group: ubuntu
    mode: 0644
  tags:
    - gen_nginx

# Move up after creating docker-compose.yml file
- name: deploy Docker Compose project for (Wordpress/MariaDB/Nginx containers)
  copy:
    # ToDo: pick up foolcontrol from a variable
    src: files/docker-compose.yml
    dest: compose-wordpress/docker-compose.yml
    owner: ubuntu
    group: ubuntu
    mode: 0644
  tags:
    - deploy_compose

  - name: Run docker-compose up
    command: docker-compose -f docker-compose.yml up -d
    args:
      chdir: /home/ubuntu/compose-wordpress/
    tags:
      - compose_run
    # ToDo: add check if docker-compose is up

  - debug:
      msg:
        - "Setup successfully complete."
        - "Wordpress instance is available on: {{ inventory_hostname }}"
        # ToDo: add line from blog URL set in nginx
    tags:
      - result
